const { loadInstruction } = require('../loadInstruction');

const systemInstruction = loadInstruction(__dirname, 'garmentCategorization.md');
const heroCategories = [
    'bags',
    'belts',
    'blazers & coats',
    'blouses',
    'bottoms',
    'bracelets',
    'dresses',
    'earrings',
    'headwear',
    'jackets',
    'jeans',
    'jumpsuits',
    'knitwear',
    'leggings',
    'necklaces',
    'outerwear',
    'pocket-squares',
    'scarves',
    'shirts',
    'shoes',
    'shorts',
    'skirts',
    'suits',
    'sunglasses',
    'sweatpants',
    'sweatshirts & hoodies',
    'swimwear',
    'ties',
    'tops',
    'trousers',
    't-shirts',
    'tunics',
    'vests',
    'socks',
    'loungewear',
    'lingerie',
    'watches',
    'cufflinks',
];

module.exports = { systemInstruction, heroCategories };
